import {Metadata} from "next";
import {Inter} from "next/font/google";
import AuthProvider from "@/components/auth-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({subsets: ["latin"]});

export default function RootLayout(props: { children: React.ReactNode }) {

    return (
        <html lang={"en"}>
        <body className={"min-h-screen bg-background text-foreground"}>
        <AuthProvider>
            {props.children}
        </AuthProvider>

        </body>
        </html>
    )
}
