import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../globals.css";
import {Providers} from "@/app/[locale]/providers";
import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "next-intl/server";
import {Navbar} from "@/components/navbar";
import ScrollToTopButton from "@/components/scroll-to-top";
import {Footer} from "@/components/footer";
import {AiFillDiscord, AiFillGithub, AiFillTwitterSquare, AiOutlineDiscord, AiOutlineTwitter} from "react-icons/ai";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const footerData = {
    registration: {
        label: "© 2021 Nextjs Starter",
    },
    socialLinks: [
        {
            icon: <AiFillGithub size={24} />,
            link: "https://github.com"
        },
        {
            icon: <AiOutlineDiscord size={24} />,
            link: "https://discord.com"
        },
        {
            icon: <AiOutlineTwitter size={24} />,
            link: "https://github.com"
        }

    ],
    footerLinkCategories: [
        {
            label: "Features",
            link: "#",
            links: [
                {
                    label: "I18n",
                    link: "#",
                },
                {
                    label: "NextAuth",
                    link: "#",
                }
            ]
        },
        {
            label: "Products",
            link: "#",
            links: [
                {
                    label: "I18n",
                    link: "#",
                },
                {
                    label: "NextAuth",
                    link: "#",
                }
            ]
        }
    ],
    partnerLinks: [
        {
            label: "Nextjs",
            link: "https://nextjs.org/",
        },
        {
            label: "Vercel",
            link: "https://vercel.com/",
        },
        {
            label: "NextUI",
            link: "https://nextui.org/",
        },
        {
            label: "Tailwindcss",
            link: "https://tailwindcss.com/",
        },
    ],
}

export default async function LocalLayout({
                                             children,
                                             params: {locale},
                                         }: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const messages = await getMessages()
    return (
        <html lang="{locale}">
        <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
            <Providers>
                <main className={'flex flex-col'}>
                    <Navbar className={'flex-auto'}/>
                    <div className={'flex-1'}>
                        {children}
                    </div>
                    <ScrollToTopButton/>
                    <Footer className={'flex-0'} {...footerData}/>
                </main>
            </Providers>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}

